
all:
	clang++ -I/usr/local/include/opencv4 -L/usr/local/lib/ -I/usr/include/octomap -g main.cpp Video.cpp -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_imgcodecs -lopencv_videoio -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_stitching -lopencv_cudaarithm -loctomath -loctomap -o binary
