
all:
	clang++ -O3 -I/usr/local/include/opencv4 -L/usr/local/lib/ -I/usr/include/octomap -g reconstruction.cpp -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_imgcodecs -lopencv_videoio -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_stitching -loctomath -loctomap -lDUO -o binary
