
all:
	clang++ -O3 -I/usr/local/include/opencv4 -I/usr/include/linux/i2c-dev -L/usr/local/lib/ -L/usr/lib/aarch64-linux-gnu/ -I/usr/include/octomap -g main.cpp -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_imgcodecs -lopencv_videoio -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_stitching -loctomath -loctomap -lopencv_cudafeatures2d -li2c -o binary
